prgrms-web-devcourse/Team-07-hey-cake-BE

- .github/workflows/ci.yml
- .gitignore
- docker-compose.yml
- src/main/resources/application.yml
- close #1 
- close #2 
- close #4 
- close #5 
- 초기 CI 설정을 위해 필요한 파일들 추가
- CI 서버에서 도커로 DB 실행을 하기 위한 docker-compose.yml
- DB 연결을 위한 기본적인 정보를 담은 application.yml
- ci 를 위한 ci.yml
> Add: CI 를 위한 설정 파일들 추가

- build.gradle
- src/docs/asciidoc/template.adoc
- #8 
- build.gradle에 Spring Rest Docs 관련 설정 추가
- html 형식의 문서화를 위한 템플릿 샘플 작성
- [문서화 노션 링크](https://www.notion.so/Spring-Rest-Docs-491742e47b8f4253a535d9bb3adeae0c)
- [참고1](https://tecoble.techcourse.co.kr/post/2020-08-18-spring-rest-docs/)
- [참고2](https://docs.spring.io/spring-restdocs/docs/current/reference/htmlsingle/)
> Chore: Spring Rest Docs 세팅

- .gitignore
- close #14 
- .gitignore 파일에 .idea/codeStyles 폴더를 추가하였음.
> Chore: .gitignore 에 .idea 폴더 추가

- build.gradle
- [#22]
- 보고서& 만족도 검사 경로에 exception 경로 추가
- 보고서& 만족도 검사 경로에 config 경로 추가
- 보고서& 만족도 검사 경로에 mapper 경로 추가
> Chore: jacoco 보고서&만족도 검사 설정 수정

- docker-compose.yml
- close #26 
- docker-compse.yml 에 container_name 을 추가해줬습니다.
> Chore: docker-compose 파일에 container_name 추가

- src/main/resources/application.yml
- close #28 
- 기존의 MySQLDialect  에서 최신 버전인 MySQL8Dialect 로 수정하였습니다.
> Chore: JPA dialect MySQL8Dialect 로 수정

- build.gradle
- [#31]
- jacoco 만족도 검사를 50%에서 0%로 하향 조저하였습니다.
> Chore: jacoco 만족도 검사 하향 조정

- .gitignore
- close #35 
- ci 시 필요하기에 .gitignore 에서 application-*.yml 제거하였습니다. 숨기고 싶은 환경 변수들은 env 파일 활용하여서 숨겼습니다.
> Chore: .gitignore 에서 application-*.yml 제거

- src/main/java/com/programmers/heycake/domain/image/event/DeleteEvent.java
- src/main/java/com/programmers/heycake/domain/image/event/ImageUploadEventListener.java
- src/main/java/com/programmers/heycake/domain/image/event/UploadRollbackEvent.java
- src/main/java/com/programmers/heycake/domain/image/model/entity/Image.java
- src/main/java/com/programmers/heycake/domain/image/service/ImageIntegrationService.java
- src/main/java/com/programmers/heycake/domain/image/service/ImageS3UploadService.java
- src/main/java/com/programmers/heycake/domain/image/service/ImageService.java
- src/main/java/com/programmers/heycake/domain/image/service/ImageUploadService.java
- src/test/java/com/programmers/heycake/domain/image/model/entity/ImageTest.java
- src/test/java/com/programmers/heycake/domain/image/service/ImageIntegrationServiceTest.java
- src/test/java/com/programmers/heycake/domain/image/service/ImageS3UploadServiceTest.java
- src/test/java/com/programmers/heycake/domain/image/service/ImageServiceTest.java
- close #43 
- 이미지 업로드 서비스 추상화
- 이미지 DB 저장과 업로드를 묶어줄 Facade 클래스 추가
- 이미지 엔티티 수정
- @TransactionalEventListener 사용하여 S3 업로드/삭제 롤백 구현은 추후에 추가하겠습니다.
> Refactor: 이미지 서비스 구조 개선

- src/main/java/com/programmers/heycake/common/exception/ErrorCode.java
- src/main/java/com/programmers/heycake/common/mapper/OfferMapper.java
- src/main/java/com/programmers/heycake/domain/market/repository/MarketRepository.java
- src/main/java/com/programmers/heycake/domain/offer/controller/OfferController.java
- src/main/java/com/programmers/heycake/domain/offer/facade/OfferFacade.java
- src/main/java/com/programmers/heycake/domain/offer/model/dto/request/OfferSaveRequest.java
- src/main/java/com/programmers/heycake/domain/offer/repository/OfferRepository.java
- src/main/java/com/programmers/heycake/domain/offer/service/OfferService.java
- src/main/java/com/programmers/heycake/domain/order/model/entity/Order.java
- src/main/java/com/programmers/heycake/domain/order/repository/OrderRepository.java
- closed #78 
- 제안 생성 기능을 구현하였습니다.
- memberId 는 임시로 받아오도록 했습니다. 회원 인증 로직이 완료되면 변경하겠습니다.
> Feat: 제안(스레드) 생성 기능 구현

- build.gradle
- src/main/java/com/programmers/heycake/common/config/QueryDslConfig.java
- close #83 
- queryDsl 의존성 추가
- configuration 생성
> Chore: queryDsl 의존성 추가 및 설정

- src/main/java/com/programmers/heycake/common/validator/Enum.java
- src/main/java/com/programmers/heycake/common/validator/EnumValidator.java
- close #79 
Enum 검증하는 커스텀 어노테이션 구현
> Feat: Enum 검증하는 커스텀 어노테이션 구현

- src/main/java/com/programmers/heycake/common/exception/GlobalExceptionHandler.java
- close #93 
- GlobalExceptionHandler 에 예외들 추가
- ConstraintViolationException - 제약 조건이 위배되었을 때 발생하는 예외
- MethodArgumentTypeMismatchException - 파라미터 타입 바인딩 못할 시 발생
- InvalidFormatException - 형식이 지정된 값의 형식이 잘못된 경우
> Fix: GlobalExceptionHandler 에 예외들 추가

- src/main/java/com/programmers/heycake/common/mapper/CommentMapper.java
- src/main/java/com/programmers/heycake/common/mapper/OfferMapper.java
- src/main/java/com/programmers/heycake/domain/comment/model/dto/response/CommentResponse.java
- src/main/java/com/programmers/heycake/domain/offer/controller/OfferController.java
- src/main/java/com/programmers/heycake/domain/offer/facade/OfferFacade.java
- src/main/java/com/programmers/heycake/domain/offer/model/dto/request/OfferSummaryRequest.java
- src/main/java/com/programmers/heycake/domain/offer/model/dto/response/OfferResponse.java
- src/main/java/com/programmers/heycake/domain/offer/model/dto/response/OfferSummaryResponse.java
- src/main/java/com/programmers/heycake/domain/offer/repository/OfferRepository.java
- src/main/java/com/programmers/heycake/domain/offer/service/OfferService.java
- closed #86 
- 
- 제안(스레드) 조회 기능을 구현하였습니다.
> Feat: 제안(스레드) 조회 기능 구현

- src/main/java/com/programmers/heycake/common/exception/ErrorCode.java
- src/main/java/com/programmers/heycake/domain/image/service/ImageIntegrationService.java
- src/main/java/com/programmers/heycake/domain/market/service/MarketService.java
- src/main/java/com/programmers/heycake/domain/member/service/MemberService.java
- src/main/java/com/programmers/heycake/domain/offer/controller/OfferController.java
- src/main/java/com/programmers/heycake/domain/offer/facade/OfferFacade.java
- src/main/java/com/programmers/heycake/domain/offer/model/entity/Offer.java
- src/main/java/com/programmers/heycake/domain/offer/service/OfferService.java
- src/main/java/com/programmers/heycake/domain/order/model/entity/Order.java
- src/test/java/com/programmers/heycake/domain/image/service/ImageIntegrationServiceTest.java
- close #40 
- offer 삭제 기능
- 해당하는 image s3, db 삭제
- context 에서 member 정보 가져와서 권한 확인
- 관련 comment 제거 메서드 생기면 추가
- 현재는 값 검증이 필요없다고 생각해서 메서드가 호출되는지만 테스트했습니다!
- 통합테스트에 header 추가 예정, save 메서드 생기면 완료 예정(로컬에선 통과함)
> Feature: 오퍼 삭제 기능 구현

- src/main/java/com/programmers/heycake/domain/offer/facade/OfferFacade.java
- src/main/java/com/programmers/heycake/domain/offer/model/entity/Offer.java
- src/main/java/com/programmers/heycake/domain/offer/service/OfferService.java
- src/main/java/com/programmers/heycake/domain/order/controller/OrderController.java
- src/main/java/com/programmers/heycake/domain/order/facade/OrderFacade.java
- src/main/java/com/programmers/heycake/domain/order/model/entity/Order.java
- src/main/java/com/programmers/heycake/domain/order/service/OrderService.java
- close #67 
- offer 삭제 API 구현
- order 삭제시에 사용할 수 있도록 권한 검증 없이 삭제 API 구현
> Feat: 주문 삭제 API 구현

- src/main/java/com/programmers/heycake/common/mapper/CommentMapper.java
- src/main/java/com/programmers/heycake/domain/comment/controller/CommentController.java
- src/main/java/com/programmers/heycake/domain/comment/facade/CommentFacade.java
- src/main/java/com/programmers/heycake/domain/comment/model/dto/request/CommentsRequest.java
- src/main/java/com/programmers/heycake/domain/comment/model/dto/response/CommentSummaryResponse.java
- src/main/java/com/programmers/heycake/domain/comment/repository/CommentRepository.java
- src/main/java/com/programmers/heycake/domain/comment/service/CommentService.java
- closed #105 
- 댓글 목록 조회 기능 구현
> Feat: 댓글 목록 조회 기능 구현

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- appspec.yml
- docker/docker-compose.yml
- scripts/deploy.sh
- close #103 
- db 관련 github secret key ci 와 cd 분리
- ci 는 local, cd 는 운영 rds
- ec2 에 codedeploy-agent 설치
- ec2 IAM 역할 설정
- jar 실행 명령어 수정
> Chore: cd 정상화

- src/main/java/com/programmers/heycake/domain/offer/controller/OfferController.java
- src/main/java/com/programmers/heycake/domain/offer/facade/OfferFacade.java
> Hotfix: 오퍼 목록 조회 API URL 변경

- src/main/java/com/programmers/heycake/domain/member/model/entity/Member.java
- src/main/java/com/programmers/heycake/domain/offer/controller/OfferController.java
- src/main/java/com/programmers/heycake/domain/offer/facade/OfferFacade.java
- src/main/java/com/programmers/heycake/domain/offer/service/OfferService.java
- closed #136 
- Member 엔티티와 Member 테이블 컬럼명 동기화
> Chore: Member 엔티티와 Member 테이블 컬럼명 동기화

- src/main/java/com/programmers/heycake/common/config/SecurityConfig.java
- close #140 
- CORS 허용 헤더에 access_token, refresh_token 추가
> Chore: CORS 허용 헤더에 access_token, refresh_token 추가

- src/main/java/com/programmers/heycake/common/config/SecurityConfig.java
- close #142 
- Origin
- Accept
- X-Requested-With
- Access-Control-Request-Method
- Access-Control-Request-Headers
- Authorization
> Chore: CORS 허용 헤더 추가

- build.gradle
- close #144 
- logback-awslogs-appender 의존성 추가
> Hotfix: logback-awslogs-appender 의존성 추가

- src/main/resources/appender/aws-debug-appender.xml
- src/main/resources/logback-spring.xml
- close #146 
- CloudWatch 에 debug 레벨도 저장하게 수정
> Chore: CloudWatch 에 debug 레벨도 저장하게 수정

- src/main/java/com/programmers/heycake/domain/member/controller/MemberController.java
- closed #148 
- 인가코드를 프론트에서 받고 해당 인가코드로 카카오 서버에서 사용자 정보를 받아 토큰을 반들어 반환하도록 변경했습니다.
> Fix: OAuth 로그인 플로우 변경

- src/main/java/com/programmers/heycake/domain/market/controller/EnrollmentController.java
- src/main/java/com/programmers/heycake/domain/market/model/dto/request/EnrollmentCreateRequest.java
- src/main/java/com/programmers/heycake/domain/market/service/EnrollmentService.java
- src/test/java/com/programmers/heycake/domain/market/controller/EnrollmentControllerTest.java
- src/test/java/com/programmers/heycake/domain/market/service/EnrollmentFacadeTest.java
- src/test/java/com/programmers/heycake/domain/market/service/EnrollmentServiceTest.java
- close #111 
- close #117 
- 로그인/회원가입 적용에 따른 회원 id 얻는 방식 변경
- 201 created 응답 시 URI 표기 방법 변경
> Fix: 로그인/회원가입 적용에 따른 업체 신청 API 수정 사항 반영

- src/main/java/com/programmers/heycake/common/exception/CustomAccessDeniedHandler.java
- src/main/java/com/programmers/heycake/common/exception/GlobalExceptionHandler.java
- close #160 
- GlobalExceptionHandler 에서 로그 찍어주도록 수정
> Fix: GlobalExceptionHandler 에서 로그 찍어주도록 수정

- src/main/java/com/programmers/heycake/domain/order/model/dto/request/MyOrderRequest.java
- src/main/java/com/programmers/heycake/domain/order/repository/HistoryQueryDslRepository.java
- src/main/java/com/programmers/heycake/domain/order/repository/OrderQueryDslRepository.java
- src/main/java/com/programmers/heycake/domain/order/service/HistoryService.java
- close #156 
- 여러 image가 있는 경우 첫번째 값만 가져올때 pageSize보다 개수가 적게 리턴되는 것 해결
- order status String이 아닌 ENUM 으로 변경
> Refactor: 주문 목록 조회 이미지 조인 관련 리팩토링

- build.gradle
- closed #138 
- 테스트를 진행 시 빌드가 실패하지 않도록 build.gradle에 spring rest docs 관련 설정을 추가했습니다.
> Chore: build.gradle에 SpringRestDocs 관련 설정 추가

- src/main/java/com/programmers/heycake/domain/comment/controller/CommentController.java
- src/main/java/com/programmers/heycake/domain/comment/model/dto/request/CommentsRequest.java
- closed #166 
- 프론트 요청에 의해 Body에서 받는 방식 -> 쿼리로 받는 방식으로 변경
> Chore: 댓글 목록 조회 OfferId 받는 방식 변경

- src/main/java/com/programmers/heycake/domain/member/model/entity/Token.java
- src/main/java/com/programmers/heycake/domain/member/service/MemberService.java
- close #62 
- refresh_token이 저장된 상태에서 다시 로그인 시 새로운 access_token, refresh_token을 발급 하도록 수정
> Fix : 재로그인시 access_token, refresh_token 새로 생성해서 저장하고 반환하도록 수정

- src/main/java/com/programmers/heycake/domain/comment/facade/CommentFacade.java
- src/main/java/com/programmers/heycake/domain/comment/service/CommentService.java
- src/main/java/com/programmers/heycake/domain/offer/facade/OfferFacade.java
- src/main/java/com/programmers/heycake/domain/order/facade/OrderFacade.java
- close #174 
- order 삭제시 offer list 못가져오는 문제 해결
- offer 삭제시 comment list 못가져오는 문제 해결
> Fix: 주문 삭제 list 문제 해결

- src/main/java/com/programmers/heycake/domain/market/model/dto/request/EnrollmentCreateRequest.java
- close #112 
- Request DTO 에 Length 관련 검증 추가
> Fix: Request DTO 에 Length 관련 검증 추가

- src/main/java/com/programmers/heycake/domain/order/controller/OrderController.java
- src/main/java/com/programmers/heycake/domain/order/facade/OrderFacade.java
- src/main/java/com/programmers/heycake/domain/order/repository/OrderQueryDslRepository.java
- src/main/java/com/programmers/heycake/domain/order/service/OrderService.java
- close #183 
- 주문 리스트 조회 OrderStatus 필터링 추가
> Feat: 주문 리스트 조회 OrderStatus 필터링 추가

- src/main/java/com/programmers/heycake/common/mapper/OrderMapper.java
- src/main/java/com/programmers/heycake/domain/order/model/dto/response/MyOrderResponse.java
- src/main/java/com/programmers/heycake/domain/order/model/dto/response/MyOrderResponseList.java
- src/main/java/com/programmers/heycake/domain/order/repository/HistoryQueryDslRepository.java
- src/main/java/com/programmers/heycake/domain/order/repository/OrderQueryDslRepository.java
- src/main/java/com/programmers/heycake/domain/order/service/HistoryService.java
- src/main/java/com/programmers/heycake/domain/order/service/OrderService.java
- close #173 
- response dto 필드값 변경
- query 변경
- response cursor Id로 변경 누락되어서 추가
> Refactor: 주문 리스트 조회 api 반환값 수정

- src/main/java/com/programmers/heycake/common/config/SecurityConfig.java
- src/main/java/com/programmers/heycake/common/exception/GlobalExceptionHandler.java
- src/main/java/com/programmers/heycake/domain/offer/controller/OfferController.java
- src/main/java/com/programmers/heycake/domain/offer/model/entity/Offer.java
- src/main/java/com/programmers/heycake/domain/order/controller/OrderController.java
- src/main/java/com/programmers/heycake/domain/order/facade/HistoryFacade.java
- src/main/java/com/programmers/heycake/domain/order/service/OrderService.java
- src/test/java/com/programmers/heycake/domain/offer/controller/OfferControllerTest.java
- src/test/java/com/programmers/heycake/domain/order/controller/HistoryControllerTest.java
- src/test/java/com/programmers/heycake/domain/order/controller/OrderControllerTest.java
- src/test/java/com/programmers/heycake/util/TestUtils.java
- close #131 
- close #132 
- close #133 
- close #135 
- api별 통합 테스트 코드 작성
- 주문 확정 생성시 offer 검증 로직 추가
- 내 주문목록 메서드 권한 필터 추가
- file change가 좀 많습니다.. 한번에 올려서 죄송합니다..
- 데이터를 만들어주기 위한 메서드가 여러 테스트에서 겹칩니다. 이 부분도 testUtil에 메서드로 만들고 싶은데, repository에 대한 의존성이 추가되야 하기 때문에 만들지 않았습니다 어떻게 하는게 좋을까요? 🧐
> Test: API 테스트 코드 작성

- src/main/java/com/programmers/heycake/domain/member/controller/MemberController.java
- src/main/java/com/programmers/heycake/domain/member/service/MemberService.java
- close #196 
- 로그 아웃시 저장된 refresh_token 삭제하는 API 구현
> Feat: 로그 아웃시 저장된 token 삭제하는 API 구현

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- src/main/resources/appender/aws-error-appender.xml
- src/main/resources/appender/aws-info-appender.xml
- close #209 
- develop 브랜치의 배포 서버를 개발용 서버로 수정
> Chore: develop 브랜치의 배포 서버를 개발용 서버로 수정

- src/main/java/com/programmers/heycake/common/mapper/OfferMapper.java
- src/main/java/com/programmers/heycake/domain/offer/facade/OfferFacade.java
- src/main/java/com/programmers/heycake/domain/offer/model/dto/response/OfferResponse.java
- src/main/java/com/programmers/heycake/domain/offer/model/dto/response/OfferSummaryResponse.java
- src/main/java/com/programmers/heycake/domain/order/repository/HistoryRepository.java
- src/main/java/com/programmers/heycake/domain/order/service/HistoryService.java
- closed #194 
- 오퍼 리스트 반환 시 추가 정보를 함께 반환하도록 추가하였습니다.
- 해당 오퍼가 어느 날짜에 오퍼를 했는지 반환
- 해당 오퍼가 주문자에 의해 지불되었는지에 대한 정보 반환
> Refactor: 오퍼 리스트 조회 시 반환 값 추가

- src/main/java/com/programmers/heycake/domain/order/service/HistoryService.java
- src/main/java/com/programmers/heycake/domain/order/service/OrderService.java
- src/test/java/com/programmers/heycake/domain/order/controller/OrderControllerTest.java
- close #215 
- 마지막 주문일시 response에 cursorId 반환값 0으로 변경
> Refactor: 내 주문 리스트 반환값 변경

- docker/init.sql
- src/main/java/com/programmers/heycake/domain/member/model/entity/Member.java
- src/main/java/com/programmers/heycake/domain/member/service/MemberService.java
- src/test/java/com/programmers/heycake/domain/market/controller/EnrollmentControllerTest.java
- src/test/java/com/programmers/heycake/util/TestUtils.java
- closed #219 
- Member 엔티티에 nickname 컬럼 추가
- CI, CD를 위한 init.sql 의 Member 테이블을 만드는 ddl 문에 nickname 컬럼 추가
> Fix: Member 엔티티에 nickname 컬럼 추가

- build.gradle
- src/main/resources/application.yml
- close #225 
- sentry 모니터링 툴 연결
- [공식 문서](https://docs.sentry.io/platforms/java/configuration/?_ga=2.135419249.1171011852.1678474596-1756340236.1678029213#options)
- [블로그](https://johnmarc.tistory.com/56)
> Chore: 모니터링 툴 연결

- src/main/java/com/programmers/heycake/common/exception/GlobalExceptionHandler.java
- close #228 
- GlobalExceptionHandler 에서 ExceptionHandler 메서드 명 수정
> Style: GlobalExceptionHandler 에서 ExceptionHandler 메서드 명 수정

- src/test/java/com/programmers/heycake/domain/market/controller/EnrollmentControllerTest.java
- close #229 
- 업체 신청 API 테스트의 실패 케이스 응답 수정
> Test: 업체 신청 API 테스트의 실패 케이스 응답 수정

- src/main/java/com/programmers/heycake/domain/order/facade/HistoryFacade.java
- src/main/java/com/programmers/heycake/domain/order/model/dto/request/HistoryControllerRequest.java
- src/test/java/com/programmers/heycake/domain/order/controller/HistoryControllerTest.java
- src/test/java/com/programmers/heycake/domain/order/facade/HistoryFacadeTest.java
- close #217 
- 결제 상태에 따라 order status 변경
> Feat: 주문 확정 API 결제 후 상태 변경하도록 수정

- src/main/java/com/programmers/heycake/domain/market/service/EnrollmentService.java
- close #232 
- 업체 신청 승인 없이 바로 되도록 한 것 롤백
> Fix: 업체 신청 승인 없이 바로 되도록 한 것 롤백

- src/test/java/com/programmers/heycake/domain/order/argument/TestArguments.java
- src/test/java/com/programmers/heycake/domain/order/controller/OrderControllerTest.java
> Test: 주문 생성 API 테스트

- src/main/java/com/programmers/heycake/common/mapper/CommentMapper.java
- src/main/java/com/programmers/heycake/common/mapper/MemberMapper.java
- src/main/java/com/programmers/heycake/domain/comment/facade/CommentFacade.java
- src/main/java/com/programmers/heycake/domain/comment/model/dto/response/CommentResponse.java
- src/main/java/com/programmers/heycake/domain/comment/model/dto/response/CommentSummaryResponse.java
- src/main/java/com/programmers/heycake/domain/member/model/dto/response/MemberResponse.java
- src/main/java/com/programmers/heycake/domain/member/service/MemberService.java
- closed #200 
- 댓글 리스트 조회 시 댓글 작성자의 nickname 도 추가하였습니다.
> Refactor: 댓글 조회 시 nickname 반환하도록 변경

- src/test/java/com/programmers/heycake/domain/market/controller/EnrollmentControllerTest.java
- src/test/java/com/programmers/heycake/util/TestUtils.java
- close #87 
- 업체 신청 정보 조회 API 테스트
> Test: 업체 신청 상세 조회 API 테스트

- src/main/java/com/programmers/heycake/domain/market/service/MarketService.java
- src/test/java/com/programmers/heycake/domain/market/controller/EnrollmentControllerTest.java
- close #88 
- close #89 
- 업체 신청 상태 변경 API 테스트 작성
> Test: 업체 신청 상태 변경 API 테스트 작성

- src/test/java/com/programmers/heycake/domain/order/controller/OrderControllerTest.java
- close #237 
- 주문 상세 조회 API 테스트
> Test: 주문 상세 조회 API 테스트

- src/main/java/com/programmers/heycake/domain/market/controller/EnrollmentController.java
- src/test/java/com/programmers/heycake/domain/market/controller/EnrollmentControllerTest.java
- src/test/java/com/programmers/heycake/util/TestUtils.java
- close #91 
- 업체 신청 리스트 조회 API 테스트 작성
> Test: 업체 신청 리스트 조회 API 테스트 작성

- src/docs/asciidoc/template.adoc
- src/test/java/com/programmers/heycake/domain/offer/controller/OfferControllerTest.java
- src/test/java/com/programmers/heycake/util/TestUtils.java
- closed #241 
- 오퍼 목록 조회 테스트 코드를 작성했습니다.
> Test: 오퍼 목록 조회 테스트

- src/docs/asciidoc/template.adoc
- src/test/java/com/programmers/heycake/domain/offer/controller/OfferControllerTest.java
- src/test/java/com/programmers/heycake/util/TestUtils.java
- closed #239 
- 오퍼 생성 테스트 코드를 작성하였습니다.
> Test: 오퍼 생성 테스트

- src/main/resources/application.yml
- close #260 
- multipart 파일 업로드 제한 사이즈 수정
> Chore: multipart 파일 업로드 제한 사이즈 수정

- src/main/java/com/programmers/heycake/common/mapper/OrderMapper.java
- src/main/java/com/programmers/heycake/domain/order/controller/OrderController.java
- src/main/java/com/programmers/heycake/domain/order/model/dto/request/OrderCreateRequest.java
- src/main/java/com/programmers/heycake/domain/order/model/dto/response/OrderGetSimpleResponse.java
- src/main/java/com/programmers/heycake/domain/order/repository/OrderQueryDslRepository.java
- src/test/java/com/programmers/heycake/domain/order/controller/OrderControllerTest.java
- close #267 
- 희망 방문 날짜가 지나서도 완료되지 않은 주문은 주문 리스트 조회에서 제외
> Chore: 주문 리스트 조회시, 희망 방문 날짜가 지나서도 완료되지 않은 주문 리스트에서 제외

- src/main/java/com/programmers/heycake/common/mapper/OrderMapper.java
- src/main/java/com/programmers/heycake/domain/order/model/dto/request/OrderCreateRequest.java
- src/main/java/com/programmers/heycake/domain/order/model/dto/response/OrderGetSimpleResponse.java
- src/test/java/com/programmers/heycake/domain/order/controller/OrderControllerTest.java
- close #273 
- 프론트와 변수명 visitTime 불일치 문제 해결
> HotFix: 프론트와 변수명 불일치 문제 해결
